# Probando Psi4

In [1]:
import psi4
mol = psi4.geometry("""
He
""")
psi4.energy('hf/cc-pvdz')
psi4.compare_values(-2.85518839, psi4.core.variable('current energy'), 5, 'SCF E')

    SCF E.................................................................................PASSED


True

# Probando ASE

In [2]:
from ase.calculators.psi4 import Psi4
from ase.build import molecule
import numpy as np

atoms = molecule('H2O')

calc = Psi4(atoms = atoms,
        method = 'b3lyp',
        memory = '500MB', # this is the default, be aware!
        basis = '6-311g_d_p_')

atoms.calc = calc
print(atoms.get_potential_energy())
print(atoms.get_forces())

-2080.2391023909363
[[-9.43607331e-13  4.74077385e-10 -3.58274865e-01]
 [-3.62505498e-14 -2.87785834e-01  1.78901194e-01]
 [ 2.95903318e-14  2.87785834e-01  1.78901194e-01]]


# Probando OpenMM

In [4]:
import openmm.testInstallation
openmm.testInstallation.main()


OpenMM Version: 7.6
Git Revision: ad113a0cb37991a2de67a08026cf3b91616bafbe

There are 2 Platforms available:

1 Reference - Successfully computed forces
2 CPU - Successfully computed forces

Median difference in forces between platforms:

Reference vs. CPU: 6.30164e-06

All differences are within tolerance.
